version: '3.8'

services:

  db:
    image: postgres:15.4
    ports:
      - 5433:5432
    restart: always
    environment:
      POSTGRES_DB: ${DB_SCHEMA:-ss2c}
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASS:-pass}